insert into movies (id, title, release_year, rating) values (1, 'Побег из Шоушенка', 1994, 9.3);
insert into movies (id, title, release_year, rating) values (2, 'Крестный Отец', 1972, 9.2);
insert into movies (id, title, release_year, rating) values (3, 'Тёмный Рыцарь', 2008, 9.0);
insert into movies (id, title, release_year, rating) values (4, 'Крестный Отец 2', 1974, 9.0);
insert into movies (id, title, release_year, rating) values (5, 'Список Шиндлера', 1993, 9.0);
insert into movies (id, title, release_year, rating) values (6, 'Властелин Колец: Возвращение Короля', 2003, 9.0);
insert into movies (id, title, release_year, rating) values (7, 'Криминальное Чтиво', 1994, 9.0);
insert into movies (id, title, release_year, rating) values (8, 'Властелин Колец: Братство Кольца', 2001, 8.8);
insert into movies (id, title, release_year, rating) values (9, 'Форрест Гамп', 1994, 8.8);
insert into movies (id, title, release_year, rating) values (10, 'Бойцовский Клуб', 1999, 8.8);
insert into movies (id, title, release_year, rating) values (11, 'Властелин Колец: Две Крепости', 2002, 8.8);
insert into movies (id, title, release_year, rating) values (12, 'Начало', 2010, 8.8);
insert into movies (id, title, release_year, rating) values (13, 'Звездные Войны V: Империя наносит ответный удар', 1980, 8.7);
insert into movies (id, title, release_year, rating) values (14, 'Матрица', 1999, 8.7);
insert into movies (id, title, release_year, rating) values (15, 'Человек-Паук: Паутина Вселенных', 2023, 8.8);
insert into movies (id, title, release_year, rating) values (16, 'Славные Парни', 1990, 8.7);
insert into movies (id, title, release_year, rating) values (17, 'Семь', 1995, 8.6);
insert into movies (id, title, release_year, rating) values (18, 'Эта замечательная жизнь', 1947, 8.6);
insert into movies (id, title, release_year, rating) values (19, 'Молчание ягнят', 1991, 8.6);
insert into movies (id, title, release_year, rating) values (20, 'Интерстеллар', 2014, 8.6);
insert into movies (id, title, release_year, rating) values (21, 'Спасти рядового Райана', 1998, 8.6);
insert into movies (id, title, release_year, rating) values (22, 'Зеленая Миля', 1999, 8.6);
insert into movies (id, title, release_year, rating) values (23, 'Звездные Войны IV: Новая надежда', 1977, 8.6);
insert into movies (id, title, release_year, rating) values (24, 'Теминатор 2: Судный день', 1991, 8.6);
insert into movies (id, title, release_year, rating) values (25, 'Назад в Будущее', 1985, 8.5);
insert into movies (id, title, release_year, rating) values (26, 'Унесенные призраками', 2001, 8.6);
insert into movies (id, title, release_year, rating) values (27, 'Пианист', 2002, 8.5);
insert into movies (id, title, release_year, rating) values (28, 'Оппенгеймер', 2023, 8.6);
insert into movies (id, title, release_year, rating) values (29, 'Психопат', 1960, 8.5);
insert into movies (id, title, release_year, rating) values (30, 'Паразит', 2019, 8.5);
insert into movies (id, title, release_year, rating) values (31, 'Гладиатор', 2000, 8.5);
insert into movies (id, title, release_year, rating) values (32, 'Король Лев', 1994, 8.5);
insert into movies (id, title, release_year, rating) values (33, 'Леон', 1994, 8.5);
insert into movies (id, title, release_year, rating) values (34, 'Американская история X', 1998, 8.5);
insert into movies (id, title, release_year, rating) values (35, 'Отпускники', 2006, 8.5);
insert into movies (id, title, release_year, rating) values (36, 'Одержимость', 2014, 8.5);
insert into movies (id, title, release_year, rating) values (37, 'Престиж', 2006, 8.5);
insert into movies (id, title, release_year, rating) values (38, '1+1', 2011, 8.5);
insert into movies (id, title, release_year, rating) values (39, 'Ла-Ла Ленд', 2016, 8.0);
insert into movies (id, title, release_year, rating) values (40, 'Тайна Коко', 2017, 8.4);
insert into movies (id, title, release_year, rating) values (41, 'Достучаться до небес', 1997, 8.6);
insert into movies (id, title, release_year, rating) values (42, 'Мстители: Финал', 2019, 8.4);
insert into movies (id, title, release_year, rating) values (43, 'Заводной апельсин', 1971, 8.3);
insert into movies (id, title, release_year, rating) values (44, 'Жизнь прекрасна', 1997, 8.6);
insert into movies (id, title, release_year, rating) values (45, 'Иван Васильевич меняет профессию', 1973, 8.2);
insert into movies (id, title, release_year, rating) values (46, 'Джокер', 2019, 8.4);
insert into movies (id, title, release_year, rating) values (47, 'Титаник', 1997, 7.8);
insert into movies (id, title, release_year, rating) values (48, 'Пираты Карибского моря: Проклятие Чёрной жемчужины', 2003, 8.0);
insert into movies (id, title, release_year, rating) values (49, 'ВАЛЛ·И', 2008, 8.4);
insert into movies (id, title, release_year, rating) values (50, 'Поймай меня, если сможешь', 2002, 8.1);
insert into movies (id, title, release_year, rating) values (51, 'Скайфолл', 2012, 7.7);
insert into movies (id, title, release_year, rating) values (52, 'Аватар', 2009, 7.8);
insert into movies (id, title, release_year, rating) values (53, 'Храброе сердце', 1995, 8.4);
insert into movies (id, title, release_year, rating) values (54, 'История игрушек', 1995, 8.3);
insert into movies (id, title, release_year, rating) values (55, 'Король Говорит!', 2010, 8.0);
insert into movies (id, title, release_year, rating) values (56, 'Бриллиантовая рука', 1969, 8.3);
insert into movies (id, title, release_year, rating) values (57, 'Монстры на каникулах', 2012, 7.1);
insert into movies (id, title, release_year, rating) values (58, 'Звёздные войны: Пробуждение Силы', 2015, 7.8);
insert into movies (id, title, release_year, rating) values (59, 'Гарри Поттер и философский камень', 2001, 7.6);
insert into movies (id, title, release_year, rating) values (60, 'Рататуй', 2007, 8.0);
insert into movies (id, title, release_year, rating) values (61, 'История игрушек 3', 2010, 8.2);
insert into movies (id, title, release_year, rating) values (62, 'Безумный Макс: Дорога ярости', 2015, 8.1);
insert into movies (id, title, release_year, rating) values (63, 'Ходячий замок', 2004, 8.2);
insert into movies (id, title, release_year, rating) values (64, 'Таинственная река', 2003, 7.9);
insert into movies (id, title, release_year, rating) values (65, 'Время', 2011, 7.9);
insert into movies (id, title, release_year, rating) values (66, 'Малавита', 2013, 6.3);
insert into movies (id, title, release_year, rating) values (67, 'Люди Икс: Дни минувшего будущего', 2014, 8.0);
insert into movies (id, title, release_year, rating) values (68, 'Амадей', 1984, 8.4);
insert into movies (id, title, release_year, rating) values (69, 'Мстители', 2012, 8.0);
insert into movies (id, title, release_year, rating) values (70, 'Зеленая книга', 2018, 8.2);
insert into movies (id, title, release_year, rating) values (71, 'Прибытие', 2016, 7.9);
insert into movies (id, title, release_year, rating) values (72, 'Джентльмены', 2019, 7.8);
insert into movies (id, title, release_year, rating) values (73, 'Алита: Боевой ангел', 2019, 7.3);